//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationStudentInfo.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_DB
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string First_Name { get; set; }
        [Required]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public string Last_Name { get; set; }
        [Required]
        [StringLength(50)]
        [DataType(DataType.Text)]
        public System.DateTime DOB { get; set; }
        [Required]
        [StringLength(50)]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be 10 digits.")]
        public string Phone { get; set; }
        [Required]
        [StringLength(50)]
        [Range(0.0, 4.0)]
        public string CGPA { get; set; }
        [Required]
        [StringLength(50)]
        public string Blood_Group { get; set; }
    }
}
