//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationdataEntry.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "Name must be at least 3 characters long.")]
        public string Title { get; set; }
        [Required]
        [Range(0, 1000000, ErrorMessage = "Salary must be between 0 and 1,000,000.")]
        public double Price { get; set; }
        [Required]
        [MaxLength(100, ErrorMessage = "Description cannot be longer than 100 characters.")]
        public int Quantity { get; set; }
        [Required]
        public string Category { get; set; }
        [Required]
        [Range(1, 10, ErrorMessage = "Salary must be between 1 and 10.")]
        public int Rating { get; set; }
    }
}
