//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLoginReg.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineBatch
    {
        public int Batch_Id { get; set; }
        public int Medicine_Id { get; set; }
        public string BatchNumber { get; set; }
        public int Quantity { get; set; }
        public double CostPrice { get; set; }
        public double SellingPrice { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
    
        public virtual MedicineBatch MedicineBatches1 { get; set; }
        public virtual MedicineBatch MedicineBatch1 { get; set; }
        public virtual MedicineBatch MedicineBatches11 { get; set; }
        public virtual MedicineBatch MedicineBatch2 { get; set; }
    }
}
