//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLoginReg.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }
        [Required]
        [StringLength(100)]

        public string User_Name { get; set; }
        [Required]
        [StringLength(100)]

        public string Password { get; set; }
        [StringLength(100)]
        [Required]
        public string Role { get; set; }
        [Required]
        [StringLength(100)]

        public string Full_Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        internal object Entry(User user)
        {
            throw new NotImplementedException();
        }

        internal void SaveChanges()
        {
            throw new NotImplementedException();
        }
    }

    public enum User_Role
    {
        Admin,
        Employer
    }
}
