// <auto-generated />
namespace WebApplicationCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InsertDatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertDatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "202505170837160_InsertDatatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
