//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDataRead.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeTable
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Pls enter name")]
        [Display(Name = "Enter Employee Name:")]
        [MaxLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "Name must be at least 3 characters long.")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Enter Join Data:")]
        public Nullable<System.DateTime> JoingDate { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Enter Employee Email:")]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Enter Employee Phone Number:")]
        [RegularExpression(@"^\d{11}$", ErrorMessage = "Phone number must be 11 digits.")]
        public string Call { get; set; }
        [Required]
        [Range(1000, 1000000, ErrorMessage = "Salary must be between 1000 and 1,000,000.")]
        [Display(Name = "Enter Employee Salay:")]
        public Nullable<double> Salay { get; set; }
        [Required]
        [Display(Name = "Enter Employee Designation:")]
        public string designation { get; set; }
    }
}
