//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDataRead.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegistrationUser
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter your name.")]
        [Display(Name = "Enter your name:")]
        [MaxLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "Name must be at least 3 characters long.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name can only contain letters and spaces.")]
        public string Full_name { get; set; }
        [Required(ErrorMessage = "Please enter your email address.")]
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        [Display(Name = "Enter your email address:")]
        [MaxLength(100, ErrorMessage = "Email cannot be longer than 100 characters.")]
        [MinLength(5, ErrorMessage = "Email must be at least 5 characters long.")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your User Id.")]
        [Display(Name = "Enter your User Id:")]
        [MaxLength(50, ErrorMessage = "User Id cannot be longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "User Id must be at least 3 characters long.")]
        public string User_Id { get; set; }
        [Required(ErrorMessage = "Please enter your password.")]
        [DataType(DataType.Password)]
        [Display(Name = "Enter your password:")]
        [MaxLength(50, ErrorMessage = "Password cannot be longer than 50 characters.")]
        [MinLength(6, ErrorMessage = "Password must be at least 6 characters long.")]
        //[RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{6,}$", ErrorMessage = "Password must contain at least one uppercase letter, one lowercase letter, and one number.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please select Role.")]
        [Display(Name = "Select Role:")]
        [MaxLength(50, ErrorMessage = "Role cannot be longer than 50 characters.")]
        [MinLength(3, ErrorMessage = "Role must be at least 3 characters long.")]
        public string Role { get; set; }
    }
    public enum UserRole
    {
        Admin,
        User
    }
}
