//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAccounrt.ConText
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Account Name:")]
        [DataType(DataType.Text)]
        public string Title { get; set; }
        [Required]
        [Display(Name = "Account Oping Data:")]
        [DataType(DataType.Date)]
        public System.DateTime OpingDate { get; set; }
        [Required]
        [Display(Name = "Account Balance:")]
        [DataType(DataType.Currency)]
        public double Balance { get; set; }
        [Required]
        [Display(Name = "Account Type:")]
        [DataType(DataType.Text)]
        [StringLength(50)]
        public string Type { get; set; }
        [Required]
        [Display(Name = "Enter Email:")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Enter Phone Number:")]
        [DataType(DataType.PhoneNumber)]
        [Phone]
        [RegularExpression(@"^\d{11}$", ErrorMessage = "Phone number must be 11 digits.")]
        public string Phone { get; set; }
    }
    public enum AccountType
    {
        Saving,
        Current,
        FixedDeposit,
    }
}
